version: 2
updates:
  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: weekly
